"""First migration

Revision ID: 3e6f6ea509c4
Revises: 4b85c8774e0c
Create Date: 2024-03-20 16:42:11.611102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e6f6ea509c4'
down_revision: Union[str, None] = '4b85c8774e0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('user_id', sa.String(length=60), nullable=False))
    op.add_column('files', sa.Column('group_id', sa.String(length=60), nullable=False))
    op.create_foreign_key(None, 'files', 'groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'files', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_column('files', 'group_id')
    op.drop_column('files', 'user_id')
    # ### end Alembic commands ###
