"""First migration

Revision ID: 4b85c8774e0c
Revises: 
Create Date: 2024-03-20 13:43:04.999802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4b85c8774e0c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('peer_messages')
    op.drop_table('user_group_association')
    op.alter_column('groups', 'description',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.drop_column('groups', 'admins')
    op.add_column('users', sa.Column('first_name', sa.String(length=60), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=60), nullable=False))
    op.add_column('users', sa.Column('_password', sa.String(length=128), nullable=False))
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=60),
               existing_nullable=False)
    op.drop_index('username', table_name='users')
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'password')
    op.drop_column('users', 'occupation')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', mysql.VARCHAR(length=25), nullable=False))
    op.add_column('users', sa.Column('date_of_birth', mysql.VARCHAR(length=10), nullable=False))
    op.add_column('users', sa.Column('occupation', mysql.VARCHAR(length=25), nullable=False))
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=128), nullable=False))
    op.add_column('users', sa.Column('lastname', mysql.VARCHAR(length=25), nullable=False))
    op.create_index('username', 'users', ['username'], unique=True)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=60),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=False)
    op.drop_column('users', '_password')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.add_column('groups', sa.Column('admins', mysql.VARCHAR(length=128), nullable=False))
    op.alter_column('groups', 'description',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.create_table('user_group_association',
    sa.Column('group_id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('user_role', mysql.VARCHAR(length=25), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='user_group_association_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_group_association_ibfk_2'),
    sa.PrimaryKeyConstraint('group_id', 'user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('peer_messages',
    sa.Column('text', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('sender_id', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('recipient_id', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('group_id', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='peer_messages_ibfk_3'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name='peer_messages_ibfk_2'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name='peer_messages_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
