"""First migration

Revision ID: 64f6fbd53dd0
Revises: 3e6f6ea509c4
Create Date: 2024-03-20 17:43:30.424111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '64f6fbd53dd0'
down_revision: Union[str, None] = '3e6f6ea509c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'owner_id',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)
    op.alter_column('files', 'group_id',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)
    op.drop_constraint('files_ibfk_3', 'files', type_='foreignkey')
    op.drop_column('files', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('user_id', mysql.VARCHAR(length=60), nullable=False))
    op.create_foreign_key('files_ibfk_3', 'files', 'users', ['user_id'], ['id'])
    op.alter_column('files', 'group_id',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False)
    op.alter_column('files', 'owner_id',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False)
    # ### end Alembic commands ###
