"""updated colum _password

Revision ID: dbcc2433c525
Revises: 281df773836b
Create Date: 2024-04-18 16:37:21.681304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dbcc2433c525'
down_revision: Union[str, None] = '281df773836b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=128), nullable=False))
    op.drop_column('users', '_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_password', mysql.VARCHAR(length=128), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
